# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seo', '0003_auto_20170126_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenormalizedSiteRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('depth', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.Relationship')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_set', to='seo.SeoSite')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='seo.SeoSite')),
            ],
        ),
        migrations.AddField(
            model_name='denormalizedsiterelationship',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_by_set', to='relationships.Relationship'),
        ),
        migrations.AddField(
            model_name='denormalizedsiterelationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_parent_set', to='seo.SeoSite'),
        ),
        migrations.AddField(
            model_name='denormalizedsiterelationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_child_set', to='seo.SeoSite'),
        ),
        migrations.AlterUniqueTogether(
            name='siterelationship',
            unique_together=set([('parent', 'child', 'by')]),
        ),
    ]
