# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20161021_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='browse_facet_order_5',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=5, verbose_name=b'Order'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='browse_facet_order_6',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=6, verbose_name=b'Order'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='browse_facet_show_5',
            field=models.BooleanField(default=False, verbose_name=b'Show'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='browse_facet_show_6',
            field=models.BooleanField(default=False, verbose_name=b'Show'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='browse_facet_text_5',
            field=models.CharField(default=b'Job Profiles', max_length=50, verbose_name=b'Heading for Custom Facet Group 5'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='browse_facet_text_6',
            field=models.CharField(default=b'Job Profiles', max_length=50, verbose_name=b'Heading for Custom Facet Group 6'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_city_order',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=5, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_company_order',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=7, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_country_order',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=3, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_facet_order',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_facet_order_2',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=2, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_facet_order_3',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=3, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_facet_order_4',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=4, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_moc_order',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_state_order',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=4, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='browse_title_order',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=6, verbose_name=b'Order'),
        ),
        migrations.AlterField(
            model_name='seositefacet',
            name='facet_group',
            field=models.IntegerField(choices=[(1, b'Facet Group 1'), (2, b'Facet Group 2'), (3, b'Facet Group 3'), (4, b'Facet Group 4'), (5, b'Facet Group 5'), (6, b'Facet Group 6')], default=1),
        ),
    ]
